//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLHOCSINH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACCOUNT
    {
        public int id_ac { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public Nullable<int> count_failed_password { get; set; }
        public Nullable<int> id_role { get; set; }
        public Nullable<bool> is_locked { get; set; }
        public Nullable<System.DateTime> LocketEndTime { get; set; }
    
        public virtual ROLE ROLE { get; set; }
    }
}
